const PROPERTY_TYPES = {
    TRAVEL_EXPENSES: "TRAVEL_EXPENSES",
    WORK_TAGS: "WORK_TAGS",
    PRODUCTIVITY_SCORE: "PRODUCTIVITY_SCORE",
    MOOD_SCORE: "MOOD_SCORE",
    MONTH: "MONTH",
    YEAR: "YEAR",
    EVENT: "EVENT",
    TRANSACTION_TYPE: "TRANSACTION_TYPE",
    TRANSACTION_EXPENSE_CATEGORY: "TRANSACTION_EXPENSE_CATEGORY",
    TRANSACTION_INCOME_CATEGORY: "TRANSACTION_INCOME_CATEGORY",
}

export default PROPERTY_TYPES