sonar.projectKey=IzePhanthakarn_next16-core-service
sonar.organization=izephanthakarn

sonar.projectName=next16-core-service
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/.next/**,**/node_modules/**,**/public/**,**/*.test.*,**/*.spec.*

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8